# Configuration

# -------- Directories --------
# Enumerates the directories to the files needed for the large scale detection
# Directories :
# - path/to/source/images : the path to the source images
# - path/to/topo : the path to the BDTOPO
# - path/to/iris : the path to the IRIS dataset, used in the postprocessing step.
# - path/to/communes : the path to the geographic information of the communes, used in the
#                      postprocessing step.
# - path/to/model : the path to the model that will be used for detection.
#
# Custom directories
# - temp : the name of the directory that stores the intermediary outputs
# - aux : the directory that contains auxiliary files (e.g. buildings)
# 
# - data : the name of the directory in which the final output (.geojson file)
#            are stored

source_images_dir : "/data/GabrielKasmi/data/ign/D069_2020"
model_dir : 'models'

source_iris_dir : '/data/GabrielKasmi/data/ign/IRIS_2021/CONTOURS-IRIS_2-1__SHP__FRA_2021-01-01/CONTOURS-IRIS/'
source_commune_dir : '/data/GabrielKasmi/data/communes'
source_topo_dir : "/data/GabrielKasmi/data/ign/TOPO/D069_2021" 

temp_dir : 'temp'
aux_dir: 'aux'
outputs_dir : 'data'


# -------- Parameters --------
# Parameters for the main pipeline script 
# - run_xx.py : True if one want to run specific parts of the pipeline, False otherwise

run_classification : True
run_segmentation : True
run_aggregation : True

# Parameters that are common to certain pipelines:
# Patch_size : used in the pre processing and the detection steps.
# - departement_number : the departement number, used in the postprocessing and main script.

patch_size : 299

# Parameters that are specific to certain pipelines

# Classification
# - device : the device to use. If None, the device is automatically set up
# - cls_batch_size : the batch_size
# - cls_threshold : the value of the thresold. Should be deliberatily low because false
#               positives (that are not located on buildings) are filtered out
# - cls_model : the name of the model to look for in the folder.

device : 'cuda'
cls_batch_size : 512
cls_threshold : 0.4
cls_model : 'model_bdappv_cls'

# Segmentation
# - seg_batch_size : the size of the segmentation batch size
# - seg_threshold : the threshold chosen for segmentation. Should be 
#                            the value that maximizes performance in order to get
#                            masks that are as accurate as possible
# - num_gpu : the number of GPU devices to use for inference
# - seg_model : the name of the model to look for in the folder.
#
seg_threshold : 0.46
num_gpu : 1
seg_batch_size : 128
seg_model : 'model_bdappv_seg'

# Postprocessing
# - compute localization of IRIS and commune : whether the detected installations
# should be given information on their commune and IRIS. 
# While IRIS comes from IGN, the administrative splitting of the communes 
# comes from OSM and can be downloaded from here : 
# https://www.data.gouv.fr/fr/datasets/decoupage-administratif-communal-francais-issu-d-openstreetmap/
# compute_iris : True
