# Configuration

# -------- Directories --------
# Enumerates the directories to the files needed for the large scale detection
# Directories :
# - path/to/source/images : the path to the source images
# - path/to/topo : the path to the BDTOPO
# - path/to/iris : the path to the IRIS dataset, used in the postprocessing step.
# - path/to/model : the path to the model that will be used for detection.
#
# Custom directories
# - outputs : the name of the directory (to consider or to create) in which
#             all intermediate results will be stored.
# - thumbnails : the name of the directory in which the thumbnails are stored


source_images_dir : "/data/GabrielKasmi/data/ign/D034/ORTHOHR_1-0_RVB-0M20_JP2-E080_LAMB93_D034_2018-01-01"
source_iris_dir : 
source_topo_dir : '/data/GabrielKasmi/data/ign/D034/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D034_2021-03-15'
model_dir : 'models'

outputs_dir : 'outputs'
thumbnails_dir : 'thumbnails'

# -------- Parameters --------
# Parameters for the main pipeline script 
# - run_xx.py : True if one want to run specific parts of the pipeline, False otherwise
# - save_map : True if one wants to generate a folium .html map of the installations.
# - map_center : a list that corresponds to the center coordinates of the map to be generated. Should be 
# in the form [lat, long] in decimal coordinates.

run_preprocessing : False
run_main_detection : True
run_postprocessing : True

save_map : True
center_latitude : 43.6291
center_longitude : 3.2501

# Parameters that are common to certain pipelines:
# Patch_size : used in the pre processing and the detection steps.
# - patch_size : the size of the input patch passed to the model.
# - departement_number : the departement number, used in the postprocessing and main script.

patch_size : 299
departement_number : 34


# Parameters that are specific to certain pipelines
# Preprocessing
# None

# Detection
# - device : the device to use. If None, the device is automatically set up
# - batch_size : the batch_size
# - threshold : the value of the thresold. Should be deliberatily low because false
#               positives (that are not located on buildings) are filtered out
# - run_detections : if true, saves the raw output dictionnary
device : 'cuda:2'
batch_size : 512
threshold : 0.2
run_detection : True

# Postprocessing
# - postprocessing_initialization : indicates whether the initialization steps should be
#                                   executed or not
postprocessing_initialization : True

